name: Submit article
description: Submit article for newsletter
title: "[Article]: "
labels: [article, triage]
assignees:
  - amezng
body:
  - type: textarea
    id: article-summary
    attributes:
      label: Provide the summary of the article.
      description: Also tell us, what did you expect to happen?
      placeholder: This article helps us to understand...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for sharing the article. Your request will be reviewed within 24 hours.
